name: Rust

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - i686-pc-windows-gnu
        include:
          - generate_name: ${{ vars.GENERATE_NAME }}
          - target: x86_64-pc-windows-gnu
            generate_name: ${{ vars.GENERATE_NAME }}.exe
          - target: i686-pc-windows-gnu
            generate_name: ${{ vars.GENERATE_NAME }}.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
#      - uses: actions/upload-artifact@v3
#        with:
#          name: ${{ matrix.target }}.zip
#          path: target/${{ matrix.target }}/release/${{ matrix.generate_name }}
      - name: upload-release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.generate_name }}
          asset_name: ${{ matrix.target }}-${{ github.ref_name }}-${{ matrix.generate_name }}
          tag: ${{ github.ref }}
